// SmartAI enum metadata (value -> label + param tooltip) for smart_scripts, transcribed from
// TrinityCore 3.3.5a SmartScriptMgr.h. Same EnumEntry pattern as util/Enums.h.
//
// Tooltips are the inline // param comments from the header, cleaned to a single line.
// Entries flagged UNUSED / DO NOT REUSE / NYI / "don't use on 3.3.5a" are still listed
// (the value is occupied) with the caveat carried into the tooltip.
#include "editors/smartai/SmartAiEnums.h"

namespace we
{
    const std::vector<EnumEntry>& SmartEventValues()
    {
        // smart_scripts.event_type (SMART_EVENT_* 0..90). Tooltip = param1..paramN meanings.
        static const std::vector<EnumEntry> table = {
            { 0,  "Update Ic",              "InitialMin, InitialMax, RepeatMin, RepeatMax" },
            { 1,  "Update Ooc",             "InitialMin, InitialMax, RepeatMin, RepeatMax" },
            { 2,  "Health Pct",             "HPMin%, HPMax%,  RepeatMin, RepeatMax" },
            { 3,  "Mana Pct",               "ManaMin%, ManaMax%, RepeatMin, RepeatMax" },
            { 4,  "Aggro",                  "NONE" },
            { 5,  "Kill",                   "CooldownMin0, CooldownMax1, playerOnly2, else creature entry3" },
            { 6,  "Death",                  "NONE" },
            { 7,  "Evade",                  "NONE" },
            { 8,  "Spellhit",               "SpellID, School, CooldownMin, CooldownMax" },
            { 9,  "Range",                  "MinDist, MaxDist, RepeatMin, RepeatMax" },
            { 10, "Ooc Los",                "HostilityMode, MaxRnage, CooldownMin, CooldownMax" },
            { 11, "Respawn",                "type, MapId, ZoneId" },
            { 12, "Target Health Pct",      "UNUSED, DO NOT REUSE" },
            { 13, "Victim Casting",         "RepeatMin, RepeatMax, spellid" },
            { 14, "Friendly Health",        "UNUSED, DO NOT REUSE" },
            { 15, "Friendly Is Cc",         "Radius, RepeatMin, RepeatMax" },
            { 16, "Friendly Missing Buff",  "SpellId, Radius, RepeatMin, RepeatMax" },
            { 17, "Summoned Unit",          "CreatureId(0 all), CooldownMin, CooldownMax" },
            { 18, "Target Mana Pct",        "UNUSED, DO NOT REUSE" },
            { 19, "Accepted Quest",         "QuestID (0 = any), CooldownMin, CooldownMax" },
            { 20, "Reward Quest",           "QuestID (0 = any), CooldownMin, CooldownMax" },
            { 21, "Reached Home",           "NONE" },
            { 22, "Receive Emote",          "EmoteId, CooldownMin, CooldownMax, condition, val1, val2, val3" },
            { 23, "Has Aura",               "Param1 = SpellID, Param2 = Stack amount, Param3/4 RepeatMin, RepeatMax" },
            { 24, "Target Buffed",          "Param1 = SpellID, Param2 = Stack amount, Param3/4 RepeatMin, RepeatMax" },
            { 25, "Reset",                  "Called after combat, when the creature respawn and spawn." },
            { 26, "Ic Los",                 "HostilityMode, MaxRnage, CooldownMin, CooldownMax" },
            { 27, "Passenger Boarded",      "CooldownMin, CooldownMax" },
            { 28, "Passenger Removed",      "CooldownMin, CooldownMax" },
            { 29, "Charmed",                "onRemove (0 - on apply, 1 - on remove)" },
            { 30, "Charmed Target",         "UNUSED, DO NOT REUSE" },
            { 31, "Spellhit Target",        "SpellID, School, CooldownMin, CooldownMax" },
            { 32, "Damaged",                "MinDmg, MaxDmg, CooldownMin, CooldownMax" },
            { 33, "Damaged Target",         "MinDmg, MaxDmg, CooldownMin, CooldownMax" },
            { 34, "Movementinform",         "MovementType(any), PointID" },
            { 35, "Summon Despawned",       "Entry, CooldownMin, CooldownMax" },
            { 36, "Corpse Removed",         "NONE" },
            { 37, "Ai Init",                "NONE" },
            { 38, "Data Set",               "Id, Value, CooldownMin, CooldownMax" },
            { 39, "Waypoint Start",         "UNUSED, DO NOT REUSE" },
            { 40, "Waypoint Reached",       "PointId(0any), pathID(0any)" },
            { 41, "Transport Addplayer",    "NONE" },
            { 42, "Transport Addcreature",  "Entry (0 any)" },
            { 43, "Transport Remove Player","NONE" },
            { 44, "Transport Relocate",     "PointId" },
            { 45, "Instance Player Enter",  "Team (0 any), CooldownMin, CooldownMax" },
            { 46, "Areatrigger Ontrigger",  "TriggerId(0 any)" },
            { 47, "Quest Accepted",         "none" },
            { 48, "Quest Obj Completion",   "none" },
            { 49, "Quest Completion",       "none" },
            { 50, "Quest Rewarded",         "none" },
            { 51, "Quest Fail",             "none" },
            { 52, "Text Over",              "GroupId from creature_text,  creature entry who talks (0 any)" },
            { 53, "Receive Heal",           "MinHeal, MaxHeal, CooldownMin, CooldownMax" },
            { 54, "Just Summoned",          "none" },
            { 55, "Waypoint Paused",        "PointId(0any), pathID(0any)" },
            { 56, "Waypoint Resumed",       "PointId(0any), pathID(0any)" },
            { 57, "Waypoint Stopped",       "PointId(0any), pathID(0any)" },
            { 58, "Waypoint Ended",         "PointId(0any), pathID(0any)" },
            { 59, "Timed Event Triggered",  "id" },
            { 60, "Update",                 "InitialMin, InitialMax, RepeatMin, RepeatMax" },
            { 61, "Link",                   "INTERNAL USAGE, no params, used to link together multiple events, does not use any extra resources to iterate event lists needlessly" },
            { 62, "Gossip Select",          "menuID, actionID" },
            { 63, "Just Created",           "none" },
            { 64, "Gossip Hello",           "noReportUse (for GOs)" },
            { 65, "Follow Completed",       "none" },
            { 66, "Event Phase Change",     "UNUSED, DO NOT REUSE" },
            { 67, "Is Behind Target",       "UNUSED, DO NOT REUSE" },
            { 68, "Game Event Start",       "game_event.Entry" },
            { 69, "Game Event End",         "game_event.Entry" },
            { 70, "Go Loot State Changed",  "go LootState" },
            { 71, "Go Event Inform",        "eventId" },
            { 72, "Action Done",            "eventId (SharedDefines.EventId)" },
            { 73, "On Spellclick",          "clicker (unit)" },
            { 74, "Friendly Health Pct",    "minHpPct, maxHpPct, repeatMin, repeatMax" },
            { 75, "Distance Creature",      "guid, entry, distance, repeat" },
            { 76, "Distance Gameobject",    "guid, entry, distance, repeat" },
            { 77, "Counter Set",            "id, value, cooldownMin, cooldownMax" },
            { 78, "Scene Start",            "don't use on 3.3.5a" },
            { 79, "Scene Trigger",          "don't use on 3.3.5a" },
            { 80, "Scene Cancel",           "don't use on 3.3.5a" },
            { 81, "Scene Complete",         "don't use on 3.3.5a" },
            { 82, "Summoned Unit Dies",     "CreatureId(0 all), CooldownMin, CooldownMax" },
            { 83, "On Spell Cast",          "SpellID, CooldownMin, CooldownMax" },
            { 84, "On Spell Failed",        "SpellID, CooldownMin, CooldownMax" },
            { 85, "On Spell Start",         "SpellID, CooldownMin, CooldownMax" },
            { 86, "On Despawn",             "NONE" },
            { 87, "Send Event Trigger",     "UNUSED NEEDS CHERRYPICK" },
            { 88, "Areatrigger Exit",       "don't use on 3.3.5a" },
            { 89, "On Aura Applied",        "SpellID, CooldownMin, CooldownMax" },
            { 90, "On Aura Removed",        "SpellID, CooldownMin, CooldownMax" },
        };
        return table;
    }

    const std::vector<EnumEntry>& SmartActionValues()
    {
        // smart_scripts.action_type (SMART_ACTION_* 0..158). Tooltip = param meanings.
        static const std::vector<EnumEntry> table = {
            { 0,   "None",                                "No action" },
            { 1,   "Talk",                                "groupID from creature_text, duration to wait before TEXT_OVER event is triggered, useTalkTarget (0/1) - use target as talk target" },
            { 2,   "Set Faction",                         "FactionId (or 0 for default)" },
            { 3,   "Morph To Entry Or Model",             "Creature_template entry(param1) OR ModelId (param2) (or 0 for both to demorph)" },
            { 4,   "Sound",                               "SoundId, onlySelf" },
            { 5,   "Play Emote",                          "EmoteId" },
            { 6,   "Fail Quest",                          "QuestID" },
            { 7,   "Offer Quest",                         "QuestID, directAdd" },
            { 8,   "Set React State",                     "state" },
            { 9,   "Activate Gobject",                    "" },
            { 10,  "Random Emote",                        "EmoteId1, EmoteId2, EmoteId3..." },
            { 11,  "Cast",                                "SpellId, CastFlags, TriggeredFlags" },
            { 12,  "Summon Creature",                     "CreatureID, summonType, duration in ms, attackInvoker, flags(SmartActionSummonCreatureFlags)" },
            { 13,  "Threat Single Pct",                   "Threat%" },
            { 14,  "Threat All Pct",                      "Threat%" },
            { 15,  "Call Areaexploredoreventhappens",     "QuestID" },
            { 16,  "Reserved 16",                         "used on 4.3.4 and higher scripts" },
            { 17,  "Set Emote State",                     "emoteID" },
            { 18,  "Set Unit Flag",                       "UNUSED, DO NOT REUSE" },
            { 19,  "Remove Unit Flag",                    "UNUSED, DO NOT REUSE" },
            { 20,  "Auto Attack",                         "AllowAttackState (0 = stop attack, anything else means continue attacking)" },
            { 21,  "Allow Combat Movement",               "AllowCombatMovement (0 = stop combat based movement, anything else continue attacking)" },
            { 22,  "Set Event Phase",                     "Phase" },
            { 23,  "Inc Event Phase",                     "Value (may be negative to decrement phase, should not be 0)" },
            { 24,  "Evade",                               "toRespawnPosition (0 = Move to RespawnPosition, 1 = Move to last stored home position)" },
            { 25,  "Flee For Assist",                     "With Emote" },
            { 26,  "Call Groupeventhappens",              "QuestID" },
            { 27,  "Combat Stop",                         "" },
            { 28,  "Removeaurasfromspell",                "Spellid (0 removes all auras), charges (0 removes aura)" },
            { 29,  "Follow",                              "Distance (0 = default), Angle (0 = default), EndCreatureEntry, credit, creditType (0monsterkill, 1event)" },
            { 30,  "Random Phase",                        "PhaseId1, PhaseId2, PhaseId3..." },
            { 31,  "Random Phase Range",                  "PhaseMin, PhaseMax" },
            { 32,  "Reset Gobject",                       "" },
            { 33,  "Call Killedmonster",                  "CreatureId," },
            { 34,  "Set Inst Data",                       "Field, Data, Type (0 = SetData, 1 = SetBossState)" },
            { 35,  "Set Inst Data64",                     "Field," },
            { 36,  "Update Template",                     "Entry" },
            { 37,  "Die",                                 "No Params" },
            { 38,  "Set In Combat With Zone",             "No Params" },
            { 39,  "Call For Help",                       "Radius, With Emote" },
            { 40,  "Set Sheath",                          "Sheath (0-unarmed, 1-melee, 2-ranged)" },
            { 41,  "Force Despawn",                       "timer" },
            { 42,  "Set Invincibility Hp Level",          "MinHpValue(+pct, -flat)" },
            { 43,  "Mount To Entry Or Model",             "Creature_template entry(param1) OR ModelId (param2) (or 0 for both to dismount)" },
            { 44,  "Set Ingame Phase Mask",               "mask" },
            { 45,  "Set Data",                            "Field, Data (only creature @todo)" },
            { 46,  "Attack Stop",                         "" },
            { 47,  "Set Visibility",                      "on/off" },
            { 48,  "Set Active",                          "on/off" },
            { 49,  "Attack Start",                        "" },
            { 50,  "Summon Go",                           "GameObjectID, DespawnTime in s" },
            { 51,  "Kill Unit",                           "" },
            { 52,  "Activate Taxi",                       "TaxiID" },
            { 53,  "Wp Start",                            "run/walk, pathID, canRepeat, quest, despawntime" },
            { 54,  "Wp Pause",                            "time" },
            { 55,  "Wp Stop",                             "despawnTime, quest, fail?" },
            { 56,  "Add Item",                            "itemID, count" },
            { 57,  "Remove Item",                         "itemID, count" },
            { 58,  "Install Ai Template",                 "UNUSED, DO NOT REUSE" },
            { 59,  "Set Run",                             "0/1" },
            { 60,  "Set Disable Gravity",                 "0/1" },
            { 61,  "Set Swim",                            "UNUSED, DO NOT REUSE" },
            { 62,  "Teleport",                            "mapID," },
            { 63,  "Set Counter",                         "id, value, reset (0/1)" },
            { 64,  "Store Target List",                   "varID," },
            { 65,  "Wp Resume",                           "none" },
            { 66,  "Set Orientation",                     "" },
            { 67,  "Create Timed Event",                  "id, InitialMin, InitialMax, RepeatMin(only if it repeats), RepeatMax(only if it repeats), chance" },
            { 68,  "Playmovie",                           "entry" },
            { 69,  "Move To Pos",                         "PointId, transport, disablePathfinding, ContactDistance" },
            { 70,  "Enable Temp Gobj",                    "despawnTimer (sec)" },
            { 71,  "Equip",                               "entry, slotmask slot1, slot2, slot3   , only slots with mask set will be sent to client, bits are 1, 2, 4, leaving mask 0 is defaulted to mask 7 (send all), slots1-3 are only used if no entry is set" },
            { 72,  "Close Gossip",                        "none" },
            { 73,  "Trigger Timed Event",                 "id(>1)" },
            { 74,  "Remove Timed Event",                  "id(>1)" },
            { 75,  "Add Aura",                            "UNUSED, DO NOT REUSE" },
            { 76,  "Override Script Base Object",         "UNUSED, DO NOT REUSE" },
            { 77,  "Reset Script Base Object",            "UNUSED, DO NOT REUSE" },
            { 78,  "Call Script Reset",                   "none" },
            { 79,  "Set Ranged Movement",                 "Distance, angle" },
            { 80,  "Call Timed Actionlist",               "ID (overwrites already running actionlist), stop after combat?(0/1), timer update type(0-OOC, 1-IC, 2-ALWAYS)" },
            { 81,  "Set Npc Flag",                        "Flags" },
            { 82,  "Add Npc Flag",                        "Flags" },
            { 83,  "Remove Npc Flag",                     "Flags" },
            { 84,  "Simple Talk",                         "groupID, can be used to make players say groupID, Text_over event is not triggered, whisper can not be used (Target units will say the text)" },
            { 85,  "Self Cast",                           "spellID, castFlags" },
            { 86,  "Cross Cast",                          "spellID, castFlags, CasterTargetType, CasterTarget param1, CasterTarget param2, CasterTarget param3, ( + the origonal target fields as Destination target),   CasterTargets will cast spellID on all Targets (use with caution if targeting multiple * multiple units)" },
            { 87,  "Call Random Timed Actionlist",        "script9 ids 1-9" },
            { 88,  "Call Random Range Timed Actionlist",  "script9 id min, max" },
            { 89,  "Random Move",                         "maxDist" },
            { 90,  "Set Unit Field Bytes 1",              "bytes, target" },
            { 91,  "Remove Unit Field Bytes 1",           "bytes, target" },
            { 92,  "Interrupt Spell",                     "" },
            { 93,  "Send Go Custom Anim",                 "UNUSED, DO NOT REUSE" },
            { 94,  "Set Dynamic Flag",                    "UNUSED, DO NOT REUSE" },
            { 95,  "Add Dynamic Flag",                    "UNUSED, DO NOT REUSE" },
            { 96,  "Remove Dynamic Flag",                 "UNUSED, DO NOT REUSE" },
            { 97,  "Jump To Pos",                         "speedXY, speedZ, targetX, targetY, targetZ" },
            { 98,  "Send Gossip Menu",                    "menuId, optionId" },
            { 99,  "Go Set Loot State",                   "state" },
            { 100, "Send Target To Target",               "id" },
            { 101, "Set Home Pos",                        "none" },
            { 102, "Set Health Regen",                    "0/1" },
            { 103, "Set Root",                            "off/on" },
            { 104, "Set Go Flag",                         "UNUSED, DO NOT REUSE" },
            { 105, "Add Go Flag",                         "UNUSED, DO NOT REUSE" },
            { 106, "Remove Go Flag",                      "UNUSED, DO NOT REUSE" },
            { 107, "Summon Creature Group",               "Group, attackInvoker" },
            { 108, "Set Power",                           "PowerType, newPower" },
            { 109, "Add Power",                           "PowerType, newPower" },
            { 110, "Remove Power",                        "PowerType, newPower" },
            { 111, "Game Event Stop",                     "GameEventId" },
            { 112, "Game Event Start",                    "GameEventId" },
            { 113, "Start Closest Waypoint",              "wp1, wp2, wp3, wp4, wp5, wp6, wp7" },
            { 114, "Move Offset",                         "" },
            { 115, "Random Sound",                        "soundId1, soundId2, soundId3, soundId4, soundId5, onlySelf" },
            { 116, "Set Corpse Delay",                    "timer" },
            { 117, "Disable Evade",                       "0/1 (1 = disabled, 0 = enabled)" },
            { 118, "Go Set Go State",                     "state" },
            { 119, "Set Can Fly",                         "UNUSED, DO NOT REUSE" },
            { 120, "Remove Auras By Type",                "UNUSED, DO NOT REUSE" },
            { 121, "Set Sight Dist",                      "UNUSED, DO NOT REUSE" },
            { 122, "Flee",                                "UNUSED, DO NOT REUSE" },
            { 123, "Add Threat",                          "+threat, -threat" },
            { 124, "Load Equipment",                      "id" },
            { 125, "Trigger Random Timed Event",          "id min range, id max range" },
            { 126, "Remove All Gameobjects",              "UNUSED, DO NOT REUSE" },
            { 127, "Pause Movement",                      "MovementSlot (default = 0, active = 1, controlled = 2), PauseTime (ms), Force" },
            { 128, "Play Animkit",                        "don't use on 3.3.5a" },
            { 129, "Scene Play",                          "don't use on 3.3.5a" },
            { 130, "Scene Cancel",                        "don't use on 3.3.5a" },
            { 131, "Spawn Spawngroup",                    "Group ID, min secs, max secs, spawnflags" },
            { 132, "Despawn Spawngroup",                  "Group ID, min secs, max secs, spawnflags" },
            { 133, "Respawn By Spawnid",                  "spawnType, spawnId" },
            { 134, "Invoker Cast",                        "spellID, castFlags" },
            { 135, "Play Cinematic",                      "entry, cinematic" },
            { 136, "Set Movement Speed",                  "movementType, speedInteger, speedFraction" },
            { 137, "Play Spell Visual Kit",               "spellVisualKitId (RESERVED, PENDING CHERRYPICK)" },
            { 138, "Override Light",                      "zoneId, overrideLightID, transitionMilliseconds" },
            { 139, "Override Weather",                    "zoneId, weatherId, intensity" },
            { 140, "Set Ai Anim Kit",                     "DEPRECATED, DO REUSE (it was never used in any branch, treat as free action id)" },
            { 141, "Set Hover",                           "0/1" },
            { 142, "Set Health Pct",                      "percent" },
            { 143, "Create Conversation",                 "don't use on 3.3.5a" },
            { 144, "Set Immune Pc",                       "0/1" },
            { 145, "Set Immune Npc",                      "0/1" },
            { 146, "Set Uninteractible",                  "0/1" },
            { 147, "Activate Gameobject",                 "GameObjectActions" },
            { 148, "Add To Stored Target List",           "varID" },
            { 149, "Become Personal Clone For Player",    "don't use on 3.3.5a" },
            { 150, "Trigger Game Event",                  "eventId, useSaiTargetAsGameEventSource (RESERVED, PENDING CHERRYPICK)" },
            { 151, "Do Action",                           "actionId (RESERVED, PENDING CHERRYPICK)" },
            { 152, "Complete Quest",                      "QuestId. Regular quests with objectives can't be completed with this action (only quests with QUEST_FLAGS_COMPLETION_EVENT, QUEST_FLAGS_COMPLETION_AREA_TRIGGER or QUEST_FLAGS_TRACKING_EVENT) (RESERVED, PENDING CHERRYPICK)" },
            { 153, "Credit Quest Objective Talk To",      "(RESERVED, PENDING CHERRYPICK)" },
            { 154, "Destroy Conversation",                "don't use on 3.3.5a" },
            { 155, "Enter Vehicle",                       "seat id (RESERVED, PENDING CHERRYPICK)" },
            { 156, "Board Passenger",                     "seat id (RESERVED, PENDING CHERRYPICK)" },
            { 157, "Exit Vehicle",                        "(RESERVED, PENDING CHERRYPICK)" },
            { 158, "Resume Movement",                     "MovementSlot (default = 0, active = 1, controlled = 2), ResumeTime (ms)" },
        };
        return table;
    }

    const std::vector<EnumEntry>& SmartTargetValues()
    {
        // smart_scripts.target_type (SMART_TARGET_* 0..30). Tooltip = param meanings.
        static const std::vector<EnumEntry> table = {
            { 0,  "None",                          "NONE" },
            { 1,  "Self",                          "Self cast" },
            { 2,  "Victim",                        "Our current target (ie: highest aggro)" },
            { 3,  "Hostile Second Aggro",          "Second highest aggro, maxdist, playerOnly, powerType + 1" },
            { 4,  "Hostile Last Aggro",            "Dead last on aggro, maxdist, playerOnly, powerType + 1" },
            { 5,  "Hostile Random",                "Just any random target on our threat list, maxdist, playerOnly, powerType + 1" },
            { 6,  "Hostile Random Not Top",        "Any random target except top threat, maxdist, playerOnly, powerType + 1" },
            { 7,  "Action Invoker",                "Unit who caused this Event to occur" },
            { 8,  "Position",                      "use xyz from event params" },
            { 9,  "Creature Range",                "CreatureEntry(0any), minDist, maxDist" },
            { 10, "Creature Guid",                 "guid, entry" },
            { 11, "Creature Distance",             "CreatureEntry(0any), maxDist" },
            { 12, "Stored",                        "id, uses pre-stored target(list)" },
            { 13, "Gameobject Range",              "entry(0any), min, max" },
            { 14, "Gameobject Guid",               "guid, entry" },
            { 15, "Gameobject Distance",           "entry(0any), maxDist" },
            { 16, "Invoker Party",                 "invoker's party members" },
            { 17, "Player Range",                  "min, max" },
            { 18, "Player Distance",               "maxDist" },
            { 19, "Closest Creature",              "CreatureEntry(0any), maxDist, dead?" },
            { 20, "Closest Gameobject",            "entry(0any), maxDist" },
            { 21, "Closest Player",                "maxDist" },
            { 22, "Action Invoker Vehicle",        "Unit's vehicle who caused this Event to occur" },
            { 23, "Owner Or Summoner",             "Unit's owner or summoner, Use Owner/Charmer of this unit" },
            { 24, "Threat List",                   "All units on creature's threat list, maxdist" },
            { 25, "Closest Enemy",                 "maxDist, playerOnly" },
            { 26, "Closest Friendly",              "maxDist, playerOnly" },
            { 27, "Loot Recipients",               "all players that have tagged this creature (for kill credit)" },
            { 28, "Farthest",                      "maxDist, playerOnly, isInLos" },
            { 29, "Vehicle Passenger",             "seatMask (0 - all seats)" },
            { 30, "Closest Unspawned Gameobject",  "entry(0any), maxDist" },
        };
        return table;
    }

    const std::vector<EnumEntry>& SmartScriptSourceTypeValues()
    {
        // smart_scripts.source_type (SMART_SCRIPT_TYPE_* 0..12). NYI / RESERVED entries are
        // noted in the tooltip; only CREATURE/GAMEOBJECT/AREATRIGGER/TIMED_ACTIONLIST are
        // functional on 3.3.5a.
        static const std::vector<EnumEntry> table = {
            { 0,  "Creature",                    "" },
            { 1,  "Gameobject",                  "" },
            { 2,  "Areatrigger",                 "" },
            { 3,  "Event",                       "NYI" },
            { 4,  "Gossip",                      "NYI" },
            { 5,  "Quest",                       "NYI" },
            { 6,  "Spell",                       "NYI" },
            { 7,  "Transport",                   "NYI" },
            { 8,  "Instance",                    "NYI" },
            { 9,  "Timed Actionlist",            "" },
            { 10, "Scene",                       "RESERVED master branch" },
            { 11, "Areatrigger Entity",          "RESERVED master branch" },
            { 12, "Areatrigger Entity Custom",   "RESERVED master branch" },
        };
        return table;
    }

    const std::vector<FlagEntry>& SmartEventFlagBits()
    {
        // SMART_EVENT_FLAG_* (SmartScriptMgr.h). Only the ones meaningful on 3.3.5a; the DIFFICULTY_*
        // and RESERVED_* bits are unused and omitted.
        static const std::vector<FlagEntry> table = {
            { 0x001, "Not Repeatable",  "event can not repeat" },
            { 0x080, "Debug Only",      "event only occurs in a debug build" },
            { 0x100, "Don't Reset",     "event will not reset in SmartScript::OnReset()" },
            { 0x200, "While Charmed",   "event occurs even if the AI owner is charmed" },
            { 0x40000000, "Ignore Chance Roll", "event occurs regardless of event_chance" },
        };
        return table;
    }

    const std::vector<FlagEntry>& SmartPhaseMaskBits()
    {
        // event_phase_mask: bit N = phase N+1 (SmartAI supports phases 1..12).
        static const std::vector<FlagEntry> table = {
            { 0x001, "Phase 1", nullptr },  { 0x002, "Phase 2", nullptr },
            { 0x004, "Phase 3", nullptr },  { 0x008, "Phase 4", nullptr },
            { 0x010, "Phase 5", nullptr },  { 0x020, "Phase 6", nullptr },
            { 0x040, "Phase 7", nullptr },  { 0x080, "Phase 8", nullptr },
            { 0x100, "Phase 9", nullptr },  { 0x200, "Phase 10", nullptr },
            { 0x400, "Phase 11", nullptr }, { 0x800, "Phase 12", nullptr },
        };
        return table;
    }
}
